export enum PlayerActionTypes {
  PLAY = "PLAY",
  PAUSE = "PAUSE",
  SET_ACTIVE_TRACK = "SET_ACTIVE_TRACK",
  SET_TRACK_DURATION = "SET_TRACK_DURATION",
  SET_CURRENT_TIME = "SET_CURRENT_TIME",
  SET_TRACK_VOLUME = "SET_TRACK_VOLUME",
}